# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_auto_20170111_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='salutation',
            field=models.CharField(default='Mr.', max_length=10),
        ),
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(blank=True, to='book.Author'),
        ),
    ]
