# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0012_auto_20170112_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='salutation',
            field=models.CharField(max_length=10),
        ),
    ]
