# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 23:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0014_remove_book_cover'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publisher',
            old_name='state_province',
            new_name='state',
        ),
    ]
